# Site settings
title: Tristan 
description: Mijn hub naar de wonderen wereld van Tristan Hollander
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tristan Hollander
user_description: Je kunt vanaf deze pagina naar al mijn websites! Zie het maar als een hub om met mij in contact te komen of meer over mij te weten te komen.
user_title: Tech Nerd 🤓
#email: contact@verstuurmemeer.nl
#twitter_username: TheDutchSmoke
github_username:  TheDutchSmoke
#gplus_username:  lorem_ipsum
 
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
